# Generated by Django 2.0.4 on 2018-10-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('Mn', 'Manager'), ('SO', 'Mechanic'), ('JR', 'Electrical'), ('SR', 'S.M.L')], default='SR', max_length=2),
        ),
    ]
