# Generated by Django 2.0.4 on 2018-10-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20181011_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_leader',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Mechanic', 'Mechanic'), ('Electrical', 'Electrical'), ('S.M.L', 'S.M.L')], default='S.M.L', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Mechanic', 'Mechanic'), ('Electrical', 'Electrical'), ('S.M.L', 'S.M.L')], default='S.M.L', max_length=20),
        ),
    ]
