# Generated by Django 2.0.4 on 2018-10-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20181011_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Mechanic', 'Mechanic'), ('Electrical', 'Electrical'), ('S.M.L', 'S.M.L'), ('unknown', 'unkown')], default='S.M.L', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_leader',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Mechanic', 'Mechanic'), ('Electrical', 'Electrical'), ('S.M.L', 'S.M.L'), ('unknown', 'unkown')], default='unknown', max_length=20),
        ),
    ]
